# Site settings
title:
description: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/NAMYEONHEE" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nam Yeon Hee
user_description: I am a college student.
user_title: Hello, and welcome.
email: ghjkl4224@naver.com
twitter_username: 
github_username: NAMYEONHEE
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']

